### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by xionkq** [xionkq/sakana-desktop#1]
- [x] 打包后程序图标替换（[8aa34e4](https://github.com/xionkq/sakana-desktop/commit/8aa34e406eb2e6c249ba32d40908e8e11027768e)）
- [x] 程序顶部透明区域添加高度（[2e75e44](https://github.com/xionkq/sakana-desktop/commit/2e75e44bc7552f7a0fc7dfe969c31824de6332b8)）
- [x] 后台模式，隐藏任务栏（[bc70fd4](https://github.com/xionkq/sakana-desktop/commit/bc70fd4a07983264e137d5d3388f8db900a04fcd)）
- [x] 工具栏图标替换，svg鼠标事件不易触发（[e3570b6](https://github.com/xionkq/sakana-desktop/commit/e3570b6472a82b9ad841f2815a4a98da75b85ef6)）
- [x] 添加README（[3cea8c0](https://github.com/xionkq/sakana-desktop/commit/3cea8c0553a77e74167680fe586525f77364c26d)）
